name: Update hosts list

on:
  schedule:
    - cron: "0 3 */3 * *"   # co 3 dni o 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Run merge script
        run: |
          chmod +x merge_hosts.sh
          ./merge_hosts.sh

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hosts.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update hosts list"
          git push
